// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0B8OAYAzjFkkxZdysNG5pU9YjjCXBAuc',
    appId: '1:182270922253:web:d69ea270d07589da33cf44',
    messagingSenderId: '182270922253',
    projectId: 'clean-architecture-ce99e',
    authDomain: 'clean-architecture-ce99e.firebaseapp.com',
    storageBucket: 'clean-architecture-ce99e.firebasestorage.app',
    measurementId: 'G-FNFVXQV74N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7a65DPawuWTqYqODRiDbHzU-0N59ALQU',
    appId: '1:182270922253:android:a12b10b3118773a433cf44',
    messagingSenderId: '182270922253',
    projectId: 'clean-architecture-ce99e',
    storageBucket: 'clean-architecture-ce99e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdj6l47Kgr8nE-iozkYYOXZpTzorVABFI',
    appId: '1:182270922253:ios:4ef7e9fb2440d20933cf44',
    messagingSenderId: '182270922253',
    projectId: 'clean-architecture-ce99e',
    storageBucket: 'clean-architecture-ce99e.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchitectureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdj6l47Kgr8nE-iozkYYOXZpTzorVABFI',
    appId: '1:182270922253:ios:4ef7e9fb2440d20933cf44',
    messagingSenderId: '182270922253',
    projectId: 'clean-architecture-ce99e',
    storageBucket: 'clean-architecture-ce99e.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchitectureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0B8OAYAzjFkkxZdysNG5pU9YjjCXBAuc',
    appId: '1:182270922253:web:b490a5f6c99afc7633cf44',
    messagingSenderId: '182270922253',
    projectId: 'clean-architecture-ce99e',
    authDomain: 'clean-architecture-ce99e.firebaseapp.com',
    storageBucket: 'clean-architecture-ce99e.firebasestorage.app',
    measurementId: 'G-PP96G3J441',
  );
}
